version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpmzs
      MYSQL_DATABASE: pmzspy
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_NAME=pmzspy
      - DB_USER=root
      - DB_PASSWORD=rootpmzs   # ✅ Corrigido aqui
      - DB_HOST=mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  simulador:
    build: 
      context: ./simulador
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
